### ISSUE TITLE
WEBSITE IS TOO GOOD

### ISSUE THREAD

**Issue by deepfriedslipper** [smellysox1/slipper-and-smellysox-s-totally-bogus-website#1]
this website is too good for me and is harming my wellbeing

that coding is too good
your bootstraps are too good

make it worse

**Comment by smellysox1** [comment]
BOOTSTRAP.

**Comment by deepfriedslipper** [comment]
thank you.

**Comment by deepfriedslipper** [comment]
issue is resolved
